/* PR Explorer · Claude V2.0 · Service Worker */
const CACHE = 'pr-explorer-claude-v2-0';
const ASSETS = [
  './', './index.html',
  './style-claude-v2.0.css',
  './app-claude-v2.0.js',
  './pr-data.js',
  './manifest.webmanifest',
  './icon-180.png', './icon-192.png', './icon-512.png',
  './gpx/PR-7-Levada-do-Moinho.gpx',
  './gpx/PR-9-Levada-do-Caldeirao-Verde.gpx',
  './gpx/PR1 PicoArieiro_zu_PicoRuivo.gpx',
  './gpx/PR1.1-vereda-da-ilha.gpx',
  './gpx/PR10-Ribeiro-Frio-Portela.gpx',
  './gpx/PR11-Balcoes.gpx',
  './gpx/PR13-Fanal.gpx',
  './gpx/PR14-Levada-dos-Cedros.gpx',
  './gpx/PR15-Ribeira-da-Janela.gpx',
  './gpx/PR16-Faja-do-Rodrigues.gpx',
  './gpx/PR18-Levada-do-Rei.gpx',
  './gpx/PR20-Vereda-do-Jardim-do-Mar.gpx',
  './gpx/PR6.2-Levada-do-Alecrim.gpx',
  './gpx/PR6.5-Vereda-do-Pico-Fernandes.gpx',
  './gpx/Pr6.1-levada-do-risco.gpx',
  './gpx/pr1.2-vereda-do-pico-ruivo.gpx',
  './gpx/pr1.3-vereda-da-encumeada.gpx',
  './gpx/pr12-caminho-real-da-encumeada.gpx',
  './gpx/pr13.1-vereda-da-palha-carga.gpx',
  './gpx/pr17-caminho-do-pinaculo-e-falhadal.gpx',
  './gpx/pr19-caminho-real-do-paul-do-mar.gpx',
  './gpx/pr2-vereda-do-urzal.gpx',
  './gpx/pr21-caminho-do-norte.gpx',
  './gpx/pr22-vereda-do-cha-o-dos-loouros.gpx',
  './gpx/pr27-glaciar-de-planalto.gpx',
  './gpx/pr28-levada-da-rocha-vermelha.gpx',
  './gpx/pr3-vereda-do-burro.gpx',
  './gpx/pr3.1-a-b-caminho-real-do-monte.gpx',
  './gpx/pr4-levada-do-barreiro.gpx',
  './gpx/pr5-vereda-das-funduras.gpx',
  './gpx/pr6-levada-das-25fontes.gpx',
  './gpx/pr6.3-vereda-da-lagoa-do-vento.gpx',
  './gpx/pr6.4-levada-velha-do-rabacal.gpx',
  './gpx/pr6.6-vereda-do-tu-nel-do-cavalo.gpx',
  './gpx/pr6.8-levada-do-paul-ii-um-caminho-para-todos.gpx',
  './gpx/pr8-vereda-da-ponta-de-sao-lourenc-o.gpx',
  './gpx/pr9.1-levada-do-caldeira-o-verde-um-caminho-para-todos.gpx',
  './kml/Route von Pestana Promenade nach PR 1.2.kml',
  './kml/Route von Pestana Promenade nach PR 1.3.kml',
  './kml/Route von Pestana Promenade nach PR 10.kml',
  './kml/Route von Pestana Promenade nach PR 11.kml',
  './kml/Route von Pestana Promenade nach PR 12.kml',
  './kml/Route von Pestana Promenade nach PR 13.1.kml',
  './kml/Route von Pestana Promenade nach PR 13.kml',
  './kml/Route von Pestana Promenade nach PR 14.kml',
  './kml/Route von Pestana Promenade nach PR 15.kml',
  './kml/Route von Pestana Promenade nach PR 16.kml',
  './kml/Route von Pestana Promenade nach PR 2.kml',
  './kml/Route von Pestana Promenade nach PR 3.1.kml',
  './kml/Route von Pestana Promenade nach PR 3.kml',
  './kml/Route von Pestana Promenade nach PR 4.kml',
  './kml/Route von Pestana Promenade nach PR 5.kml',
  './kml/Route von Pestana Promenade nach PR 6.1.kml',
  './kml/Route von Pestana Promenade nach PR 6.2.kml',
  './kml/Route von Pestana Promenade nach PR 6.3.kml',
  './kml/Route von Pestana Promenade nach PR 6.4.kml',
  './kml/Route von Pestana Promenade nach PR 6.5.kml',
  './kml/Route von Pestana Promenade nach PR 6.6.kml',
  './kml/Route von Pestana Promenade nach PR 6.8.kml',
  './kml/Route von Pestana Promenade nach PR 6.kml',
  './kml/Route von Pestana Promenade nach PR 7.kml',
  './kml/Route von Pestana Promenade nach PR 8.kml',
  './kml/Route von Pestana Promenade nach PR 9.1.kml',
  './kml/Route von Pestana Promenade nach PR 9.kml',
  './kml/Route von Pestana Promenade nach PR17.kml',
  './kml/Route von Pestana Promenade nach PR18.kml',
  './kml/Route von Pestana Promenade nach PR19.kml',
  './kml/Route von Pestana Promenade nach PR20.kml',
  './kml/Route von Pestana Promenade nach PR21.kml',
  './kml/Route von Pestana Promenade nach PR22.kml',
  './kml/Route von Pestana Promenade nach PR27.kml',
  './kml/Route von Pestana Promenade nach PR28.kml',
  './kml/Route von Pestana Promenade nach PR_1.1.kml',
  './kml/Route von Pestana Promenade nach PR_1.kml'
];
self.addEventListener('install', e => {
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(ASSETS)).then(() => self.skipWaiting()));
});
self.addEventListener('activate', e => {
  e.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});
self.addEventListener('fetch', e => {
  e.respondWith(caches.match(e.request).then(r => r || fetch(e.request)));
});
